# Generated by Django 4.1.7 on 2023-04-13 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='answers_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.TextField(max_length=1000, verbose_name='Respuesta1')),
                ('answer2', models.TextField(max_length=1000, verbose_name='Respuesta2')),
                ('answer3', models.TextField(max_length=1000, verbose_name='Respuesta3')),
                ('answer4', models.TextField(max_length=1000, verbose_name='Respuesta4')),
                ('answer5', models.TextField(max_length=1000, verbose_name='Respuesta5')),
                ('answer6', models.TextField(max_length=1000, verbose_name='Respuesta6')),
                ('answer7', models.TextField(max_length=1000, verbose_name='Respuesta7')),
                ('answer8', models.TextField(max_length=1000, verbose_name='Respuesta8')),
                ('answer9', models.TextField(max_length=1000, verbose_name='Respuesta9')),
                ('answer10', models.TextField(max_length=1000, verbose_name='Respuesta10')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respueta_Usuario',
                'verbose_name_plural': 'Respuestas_usuario',
                'db_table': 'answers_user',
                'ordering': ['id'],
            },
        ),
    ]
