# Generated by Django 4.1.7 on 2023-04-13 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers_user',
            old_name='id_user',
            new_name='user',
        ),
    ]
