# Generated by Django 4.2 on 2023-04-18 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backds', '0003_alter_answers_user_options_alter_answers_user_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerschatgpt',
            name='user',
        ),
        migrations.AddField(
            model_name='answerschatgpt',
            name='usergpt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answerschatgpt',
            name='cliente_ideal',
            field=models.TextField(max_length=1000, verbose_name='cliente_ideal'),
        ),
    ]
