# Generated by Django 4.2 on 2023-04-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backds', '0004_remove_answerschatgpt_user_answerschatgpt_usergpt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerschatgpt',
            old_name='usergpt',
            new_name='user',
        ),
    ]
