# Generated by Django 4.2 on 2023-05-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backds', '0006_answers_user_created_at_answerschatgpt_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers_user',
            name='name_e_p',
            field=models.TextField(default=522374, max_length=15, verbose_name='Nombre_empresa_proyecto'),
            preserve_default=False,
        ),
    ]
