# Generated by Django 4.2 on 2023-05-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backds', '0007_answers_user_name_e_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers_user',
            name='name_e_p',
            field=models.TextField(max_length=30, verbose_name='Nombre_empresa_proyecto'),
        ),
    ]
