# Generated by Django 4.2 on 2023-08-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backds', '0008_alter_answers_user_name_e_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers_user',
            old_name='answer7',
            new_name='actividades',
        ),
        migrations.RenameField(
            model_name='answers_user',
            old_name='answer4',
            new_name='canales',
        ),
        migrations.RenameField(
            model_name='answers_user',
            old_name='answer3',
            new_name='propuesta',
        ),
        migrations.RenameField(
            model_name='answers_user',
            old_name='answer6',
            new_name='recursos',
        ),
        migrations.RenameField(
            model_name='answers_user',
            old_name='answer5',
            new_name='relaciones',
        ),
        migrations.RenameField(
            model_name='answers_user',
            old_name='answer2',
            new_name='segmento',
        ),
        migrations.RenameField(
            model_name='answers_user',
            old_name='answer1',
            new_name='segmento_propuesta',
        ),
        migrations.RenameField(
            model_name='answers_user',
            old_name='answer8',
            new_name='socios',
        ),
        migrations.RemoveField(
            model_name='answers_user',
            name='answer10',
        ),
        migrations.RemoveField(
            model_name='answers_user',
            name='answer9',
        ),
    ]
