# Generated by Django 4.2 on 2023-08-29 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backds', '0009_rename_answer7_answers_user_actividades_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerschatgpt',
            old_name='estructura_costes',
            new_name='actividades',
        ),
        migrations.RenameField(
            model_name='answerschatgpt',
            old_name='soluciones',
            new_name='canales',
        ),
        migrations.RenameField(
            model_name='answerschatgpt',
            old_name='propuesta_valor',
            new_name='propuesta',
        ),
        migrations.RenameField(
            model_name='answerschatgpt',
            old_name='flujo_ingresos',
            new_name='recursos',
        ),
        migrations.RenameField(
            model_name='answerschatgpt',
            old_name='canal',
            new_name='relaciones',
        ),
        migrations.RenameField(
            model_name='answerschatgpt',
            old_name='cliente_ideal',
            new_name='segmento',
        ),
        migrations.RenameField(
            model_name='answerschatgpt',
            old_name='problema',
            new_name='segmento_propuesta',
        ),
        migrations.RenameField(
            model_name='answerschatgpt',
            old_name='metricas',
            new_name='socios',
        ),
        migrations.RemoveField(
            model_name='answerschatgpt',
            name='ventaja_diferencial',
        ),
    ]
