# Generated by Django 4.2 on 2023-08-29 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backds', '0010_rename_estructura_costes_answerschatgpt_actividades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerschatgpt',
            name='segmento_propuesta',
        ),
    ]
