# Generated by Django 4.2 on 2023-08-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backds', '0011_remove_answerschatgpt_segmento_propuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerschatgpt',
            name='actividades',
        ),
        migrations.RemoveField(
            model_name='answerschatgpt',
            name='canales',
        ),
        migrations.RemoveField(
            model_name='answerschatgpt',
            name='propuesta',
        ),
        migrations.RemoveField(
            model_name='answerschatgpt',
            name='recursos',
        ),
        migrations.RemoveField(
            model_name='answerschatgpt',
            name='relaciones',
        ),
        migrations.RemoveField(
            model_name='answerschatgpt',
            name='segmento',
        ),
        migrations.RemoveField(
            model_name='answerschatgpt',
            name='socios',
        ),
        migrations.AddField(
            model_name='answerschatgpt',
            name='actividades_gpt',
            field=models.TextField(default='null', max_length=700, verbose_name='actividades_gpt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerschatgpt',
            name='canales_gpt',
            field=models.TextField(default='ValorPredeterminado', max_length=700, verbose_name='canales_gpt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerschatgpt',
            name='propuesta_gpt',
            field=models.TextField(default='Ninguna actividad', max_length=700, verbose_name='propuesta_gpt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerschatgpt',
            name='recursos_gpt',
            field=models.TextField(default='Ninguna actividad', max_length=700, verbose_name='recursos_gpt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerschatgpt',
            name='relaciones_gpt',
            field=models.TextField(default='Ninguna actividad', max_length=700, verbose_name='relaciones_gpt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerschatgpt',
            name='segmento_gpt',
            field=models.TextField(default='Ninguna actividad', max_length=1000, verbose_name='segmento_gpt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerschatgpt',
            name='socios_gpt',
            field=models.TextField(default='Ninguna actividad', max_length=700, verbose_name='socios_gpt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answers_user',
            name='actividades',
            field=models.TextField(max_length=1000, verbose_name='actividades'),
        ),
        migrations.AlterField(
            model_name='answers_user',
            name='canales',
            field=models.TextField(max_length=1000, verbose_name='canales'),
        ),
        migrations.AlterField(
            model_name='answers_user',
            name='propuesta',
            field=models.TextField(max_length=1000, verbose_name='propuesta'),
        ),
        migrations.AlterField(
            model_name='answers_user',
            name='recursos',
            field=models.TextField(max_length=1000, verbose_name='recursos'),
        ),
        migrations.AlterField(
            model_name='answers_user',
            name='relaciones',
            field=models.TextField(max_length=1000, verbose_name='relaciones'),
        ),
        migrations.AlterField(
            model_name='answers_user',
            name='segmento',
            field=models.TextField(max_length=1000, verbose_name='segmento'),
        ),
        migrations.AlterField(
            model_name='answers_user',
            name='segmento_propuesta',
            field=models.TextField(max_length=1000, verbose_name='segmento-propuesta'),
        ),
        migrations.AlterField(
            model_name='answers_user',
            name='socios',
            field=models.TextField(max_length=1000, verbose_name='socios'),
        ),
    ]
