# Generated by Django 4.2 on 2023-08-29 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backds', '0013_remove_answers_user_segmento_propuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento_image1', models.URLField()),
                ('segmento_image2', models.URLField()),
                ('propuesta_image1', models.URLField()),
                ('propuesta_image2', models.URLField()),
                ('canales_image', models.URLField()),
                ('relaciones_image', models.URLField()),
                ('recursos_image', models.URLField()),
                ('actividades_image', models.URLField()),
                ('socios_image1', models.URLField()),
                ('socios_image2', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
