# Generated by Django 4.2 on 2023-08-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backds', '0015_alter_generatedimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='actividades_image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='canales_image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='propuesta_image1',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='propuesta_image2',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='recursos_image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='relaciones_image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='segmento_image1',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='segmento_image2',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='socios_image1',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='socios_image2',
            field=models.URLField(max_length=1000),
        ),
    ]
