# Generated by Django 4.2 on 2023-09-01 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backds', '0017_logoproyect'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_corrida_financiera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_activo_fijo', models.JSONField()),
                ('data_activo_diferido', models.JSONField()),
                ('data_capital_trabajo_mano_obra', models.JSONField()),
                ('data_capital_trabajo_servicios', models.JSONField()),
                ('data_capital_trabajo_servicios_mantto', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'corrida_financiera',
                'verbose_name_plural': 'corridas_financieras',
                'db_table': 'corrida_financiera',
                'ordering': ['id'],
            },
        ),
    ]
