# Generated by Django 4.2 on 2023-09-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backds', '0020_data_corrida_financiera_data_total_inversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_corrida_financiera',
            name='data_total_inversion',
        ),
        migrations.AddField(
            model_name='data_corrida_financiera',
            name='data_total_invercion',
            field=models.JSONField(null=True),
        ),
    ]
