# Generated by Django 4.2 on 2023-09-05 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backds', '0021_remove_data_corrida_financiera_data_total_inversion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_corrida_financiera',
            old_name='data_total_invercion',
            new_name='data_total_inversion',
        ),
    ]
