# Generated by Django 4.2 on 2023-09-11 17:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backds', '0024_data_corrida_financiera_data_memorias_calculo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailCredential',
            new_name='credenciales',
        ),
    ]
