# Generated by Django 4.2 on 2023-09-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backds', '0025_rename_emailcredential_credenciales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='credenciales',
        ),
    ]
