# Generated by Django 4.2 on 2023-09-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backds', '0027_emailcredential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailCredential',
        ),
    ]
