# Generated by Django 4.2 on 2023-09-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backds', '0028_delete_emailcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='costos_image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='ingresos_image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='actividades_image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='canales_image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='propuesta_image1',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='propuesta_image2',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='recursos_image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='relaciones_image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='segmento_image1',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='segmento_image2',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='socios_image1',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='socios_image2',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
